# Generated by Django 3.2 on 2021-05-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0007_mascota_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(default='mascotas/sinimagen.jpg', upload_to='mascotas'),
        ),
    ]
